Vet clinic database: query multiple tables
Fombi-Favour/vet-clinic-sql pull request #3
Opened 2023-10-24 22:57 UTC by Fombi-Favour

In this activity, we:
- created `owners` and `species` tables
- updated the `animals` table
- made use of the foreign keys

## Queries
- >What animals belong to Melody Pond?
![project3-sc1](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/93bd80a6-d57a-4a39-8b28-b82210ec223d)
- >List of all animals that are pokemon (their type is Pokemon).
![project3-sc2](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/1d99bfc4-0462-4ecc-8f4c-ed6ddf1d6746)
- >List all owners and their animals, remember to include those that don't own any animal.
![project3-sc3](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/d4d5f8b1-2f19-4df7-9d06-34fc80dbc6a4)
- >How many animals are there per species?
![project3-sc4](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/30880cec-7e00-4d3f-a3ba-186efbd00ca8)
- >List all Digimon owned by Jennifer Orwell.
![project3-sc5](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/5c85649d-f33a-40a6-b094-e457c9e0b2ce)
- >List all animals owned by Dean Winchester that haven't tried to escape.
![project3-sc6](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/322c89f0-d558-4aaf-9a64-c5c13d7c6d3f)
- >Who owns the most animals?
![project3-sc7](https://github.com/Fombi-Favour/vet-clinic-sql/assets/77404317/fd872977-f000-4a3e-93f3-96f255a34eb8)

2023-10-24 23:31 UTC, skyv26 requested changes
## Hi @Fombi-Favour, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGYyYWNkMjRkY2JjYjg1MjY1M2NjYTNkNWNiNTQwN2EyZGZmNWM5YSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/m3864rBwwBTKMAbpn3/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 23:31 UTC, skyv26 commented on data.sql
> +UPDATE animals SET species_id=1 WHERE species_id IS NULL;
- [ ] Dear @Fombi-Favour you did a great job, and your query is working fine. But I think your approach is not correct, you are trying to update things by adding the id statically, just think about a scenario, where you need to make the changes but you don't have any idea about the `ID` of the species. Kindly look at the below hint to understand to update the column data more efficiently.

## Hint
![image](https://github.com/Fombi-Favour/vet-clinic-sql/assets/66476329/408a13bf-f04a-4572-83b6-1924818475a3)

2023-10-25 11:41 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @Fombi-Favour 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use queries for each question ✔
- Proper use of GitFlow ✔ 
- Descriptive PR title with a great organized summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 12:00 UTC, merged

2023-11-22 13:21 UTC, zeff96 reviewed
### Status: APPROVED :green_circle: 
Hi @Fombi-Favour , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media3.giphy.com/media/3oz9ZE2Oo9zRC/100.webp?cid=ecf05e47l7u4ffcrj4i2w8ahl9hbx4xy8q1gzww9df152fuy&ep=v1_gifs_search&rid=100.webp&ct=g)

## Highlights
:heavy_check_mark: Descriptive PR
:heavy_check_mark: Correct GitFlow


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._